### PR TITLE
Change die() to throw new Exception

### PR DESCRIPTION
**Pull request by ImLoadingUuU**
So try catch could handle it

### CODE REVIEW

**Comment by ImLoadingUuU** [comment]
die() will stop execution of file.

**Comment by ImLoadingUuU** [comment]
截圖 2023-07-23 上午8 03 11


> Correct me if I am wrong here, but doesn't die() stop execution of the file, meaning the exception will not be thrown?
> 
> https://www.php.net/die

if use die(). Exception will not be shown. it will only show error string "Like VistapanelApi_Error: Blablablablablablabla"
so Chippytech why you close this PR?

**Review by 4yx — CHANGES_REQUESTED** [review]
I believe it would be better if ``classError`` was removed completely and all methods were modified to throw exceptions where needed.

**Comment by ImLoadingUuU** [comment]
Thanks you reopen the PR. I will change it when i have times

**Comment by ImLoadingUuU** [comment]
@4yx All classError has been switched to throw new Exception.

**Comment by SpookyKipper** [comment]
But this may not be caught and treat an error as success on some system (like mine)

**Comment by ImLoadingUuU** [comment]
> But this may not be caught and treat an error as success on some system (like mine, I don't catch exceptions at all)
> 
> I'd suggest adding a variable to the (currently removed) classError function, and let users choose between die or exception

they could just
```php
try {
   $vpApi = new VistapanelApi();
   $vpApi->doSomething()
} catch (Exception $e){
  die($e);
}
```

**Review by SpookyKipper — APPROVED** [review]
Looks cool to me then

**Review by 4yx — APPROVED** [review]

**Pull request merged**
